### ISSUE TITLE
Can't deliver broadcast

### ISSUE THREAD

**Issue by GabrielCalin** [SmallTsai/cordova-plugin-notification-listener#1]
I get this fatal exception whenever my (Xiaomi) phone gets a new notification:

_android.app.RemoteServiceException: can't deliver broadcast_

Not sure if it's related, but I always get that I have permission, but notification service is not running. When I try to toggle it, nothing happens, no success or fail is triggered.

**Comment by SmallTsai** [comment]
@GabrielCalin I have done some code changes, please try again.

**Comment by GabrielCalin** [comment]
Thanks soooo much for switching to LocalBroadcastManager, I was just pulling the repo to do it myself and now you saved my time. It works great now, I get all notifications.

2 small questions, if you have the time:

- do you know why I get notifications with no title and text for Spotify? Other media apps I tested, like Plex, work fine.
- do you know if there's any way the notification could contain info about media being paused or playing (maybe from the on going notification flag)?

If there's too much trouble, I will try to figure them out myself. I could also open an enhancement request.
